### PR TITLE
Add tests for `state: absent`

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by jugglinmike** [comment]
These tests demonstrate an inconsistency in the module's return value as it is implemented today.

I'd like to follow up with a commit to normalize that value, but that would be a breaking change. Would it be accepted?

**Comment by DrMegahertz** [comment]
You're right. I'm not entirely sure why the decision was made to return a different result for the 'absent'-case, but it seems like a bad practice to me.

The arguments given to `exit_json` are mostly for the sake of being verbose IIRC, so it really shouldn't break anything. Unless people are doing funky stuff by calling this module programatically instead of using the cloudflare api directly. But in that case; let em burn.

Go ahead if you'd like to make the return value more consistent.

Oh, and there's an 's' missing in the `test_remove_exiting_record` method. :)

**Comment by jugglinmike** [comment]
Thanks for the input! I think this is all set. I've changed the return value in a separate commit just to help document that the change was intentional.

**Comment by DrMegahertz** [comment]
:+1:

**Comment by DrMegahertz** [comment]
Thanks again! :)

**Comment by jugglinmike** [comment]
Thank you!

**Pull request merged**
